language: node_js
node_js:
 - "8"
notifications:
  email: false
before_deploy:
- test $TRAVIS_TEST_RESULT = 0
jobs:
  include:
    - stage: run tests
      script:
        # Ensure Travis aborts without running tests if the lockfile needs updating
        - set -e
        - ./scripts/check-lockfile.sh
        - yarn test
    - stage: check for new release
      script:
      # Ensure Travis aborts without creating a release if version hasn't changed
      - set -e
      - ./scripts/check-release-version.sh
      deploy:
        # This whole section is only run if check-release-version exits without
        # error, which only happens when there is a new release to roll out.
        # 
        # GitHub releases are created from the tagged commit. All other deploy
        # providers are only triggered on the master branch.
        #
        # Heroku is configured to automatically deploy the following branches
        # once CI passes:
        # master         -> http://idsk-elements.herokuapp.com/
        #                -> http://idsk-elements-review.herokuapp.com/
        # latest-release -> http://idsk-elements-sass-release.herokuapp.com/
        
        # Create a new tag on Github and update the latest-release branch
        - provider: script
          script: ./scripts/create-release.sh

        # Update the NPM package (https://www.npmjs.com/package/idsk-elements-sass)
        - provider: script
          script: 
          - echo "Deploying to npm ..."
          - cd packages/idsk-elements-sass/

        - provider: npm
          email: ernest.walzel+idsk@slovensko.digital
          api_key:
            secure: "Hnco+VyfeGJDLnxk0m9KY7t3lhaeTWD7aFDN/LMpBXqUmdc2+hSAoAYLfMqgW6wjSTOnpFpEdbXhIhN51gD5lDmdz3Nat9iuQKPNVmij30dZrJm0Esr25R1gxfBg5fn0YmVHhxKvga2kN8tYTnXCXh3r8HrsTJj7jndVxqGFipfYLxrFO9bE6l2KfPuVi6+l2RCzzlfdfPUp9dfqA+yh5QCXdTgNfkk1B/at/y8ehqS+nVVmlCFxWDoVYf0kONr2P9RDx3HjR5Helrtq7pJ/cFKOtZ7P7TAxxLpWX9JrBmbWjK/hD2THuVkNUnBMgCJWGkVQFBWN0chgSfskY8y6HIRWSFyxEvyM2ecyIKMab1PhzTVqFJSpz9MaOEnDYOrnit+EoBaYBgWg8agXQV1HP+DLdhwAAEcf6QiuBtYFA1f3Ljz+wQPVedQvcZwver1S3GSX2/Z+8q2YMHszdNRtbpjNUNNIBi7uHHV0e/3EwP0kCrEZ/QymxBev+gQ+T3xQkLKYzIbvk9fZpkQoNTBXZjaUCL/rwGfR49XwprDgwkd1n2rzU5NSOD45mInQAj8AhPz4V5dRjihOybdoe06MCLjJf8ws/OklG7wHv3xdtjRQZ9VtnKb/A5qle1JG4mbC37jq3oIs7/fsQMZ2/KJQjn8cqttZABzYwvdO9yC3utA="

        # Upload the contents of packages/idsk-elements-sass/ to GitHub releases
        - provider: script
          script: 
          - echo "Deploying to GitHub releases ..."

        - provider: releases
          api_key:
            secure: "k9psSHgQMduQ0EGbWM5w26xoMmjMRuWpdO2N8BrdP3IG9RKBOBfuJEwRMxORbTLDQ5Pb9e8r7Ptc4VUbA4ndx67kex07JV7FQRiOFJfWKwJPLJZhr00p3hSt5L79ey7uwUKRs+YXJDCIl2QVogv9DNkVFkPUKIFt7lyEBojaUrvy8rPZ+qAqQiFhlsoFmQJcMs2/eRtF75SubsUSSg5MfP5qAtaU814klWOxES8lGm8Vjv6ia/tamHbFzAoR2CDz+66R+g+O1kkeEOFFs0zR4G3vNiTo0UqmlDwVae+f411qC1GOBEU4XEbI3i4Y59pXUgcJxTV5PlMHESBNnAU453Q7XvWB6+Kt4hqc0mxiVTOvMXb4reEFhSvqtV7Q7GqUFSIvPmHlAPqS235gTR7wwt790MJJYX2c5jeOsr7NqDuTet2uwTiizJJtQoVbQ8pHSndSZ1WKgUPif/eehgEJzNkjvteOJ0uDvEG373LPY8gJZH8sBoZQt1vYJNUp8Y4dpooxZ3sAlqrRrlKInqJACcxXpp3ja5LpPa/Y0ZNIDiwOfCEnS9giWYHDLDj7C8K4TTCi6anTqmp+ArE8gqVEq3itR2bI7+3LzQdYDUGOQ9cI/F40HBQqRgBELlENFxtpRi960f7G0o7poXFIslF746kflQG8p4I0xbBLHV3dXp4="
          file_glob: true
          file: packages/idsk-elements-sass/*
          skip_cleanup: true
          on:
            tags: true
            all_branches: true

  # Allow this stage to fail without breaking the build (as we only release when
  # the version changes)
  allow_failures:
    - stage: check for new release
sudo: false
env:
  global:
    secure: eFtS+dlf00c3h4Rpp1FSZw6wOmZPmY4lYbqPV6MQa+VUgh+FRbUYOjDJP3UFaTsWNxMIL4mhEKFYLnkVftBdz1FgPjhIO3jNXleGMgVVedtD+qo5hTu1KI39t68K2YcELx9+kzeccX77WVmv/qJTVg7+f84WP9ebzVOJCQprJuw=
